spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.42/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  ##@JsonInclude(JsonInclude.Include.NON_NULL)//如果是空不返回
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
